### ISSUE TITLE
Bug: Dropdown component not opening on click

### ISSUE THREAD

**Issue by MrChaker** [markmead/hyperui#113]
Not sure if this is a bug or it's meant to be like this , the dropdown components menu should toggle when clicking .

**Comment by markmead** [comment]
Seems fine to me.

**Comment by markmead** [comment]
Oh I thought this was on HyperJS. 😅

Nope, the dropdown menus shouldn't toggle, these aren't interactive components as I don't want to make the assumption of how you write JavaScript.
