### ISSUE TITLE
License required

### ISSUE THREAD

**Issue by adroste** [markmead/hyperui#12]
I like your components, they are clean and simple and a good starting point.
I'd like to use them (respectively derived work) in a commercial product.
However, I could not find a license info. (I was hoping to find something like MIT.)
Could you add one?

**Comment by markmead** [comment]
Thanks for pointing that out! Sorry, it wasn't included.

It's been added with #13

**Comment by vhscom** [comment]
I would suggest switching this over to zero BSD because the MIT license has a requirement that it is contained with every piece of code copied whereas the bsd-0 clause does not.
