### ISSUE TITLE
New Component Request

### ISSUE THREAD

**Issue by Aniket1026** [markmead/hyperui#127]
Dark mode button

In the button section we can have dark mode buttons . People who want to toggle there theme do dark mode can use this component and add this button in their site or App . 

https://user-images.githubusercontent.com/92184189/181443610-b6d7d761-2463-490f-8e35-402c02b20477.mp

Also a simple toggling button would be really nice to have people can use toggling button to toggle anything in general 

https://user-images.githubusercontent.com/92184189/181471297-448b12d6-ee28-4e48-8c7f-de315c27de5e.mp4

**Comment by Aniket1026** [comment]
If the changes are good . I'd like to work and contribute.

**Comment by markmead** [comment]
I wouldn't call these "dark mode buttons" to me these are toggles and would be a part of "Application UI".

Looking forward to seeing what you create! 🥳

**Comment by Aniket1026** [comment]
Thank you so much for letting me to have the chance to work on this 😃😃 .
