### ISSUE TITLE
Enhanced use case for the examples.

### ISSUE THREAD

**Issue by jessycormier** [markmead/hyperui#129]
Hello, 

I'm writing to suggest enhanced suggestions on how to use component designs in a project. Sometimes Having something visually nice doesn't really translate to a working website flow. 

Out of the box, for example, https://www.hyperui.dev/components/application-ui/side-menu the idea of the side menu is great but without more understanding, it doesn't work well with a better understanding of the layout and how it can fit into this design.

Some thing I would be looking to retain is the natural scrollbar for the browser rather than a scrollable container (better rendering performance).

This site has some fantastic starting point elements though and of course, it's up to us to enhance and figure out how to use them in our use cases. I'm just thinking of the next step for enhanced or maybe "advanced" use cases for the website to display for consumers of these components.

**Comment by jessycormier** [comment]
To provide a solution for the hypothetical I mentioned I'll take the code snippet from the link provided and provide a simple solution.

- Add `fixed` class to the side-menu.
- Add an equal width margin (or more) to a div so the content will not hide under the side menu)

```html
<div class="flex flex-col justify-between w-16 h-screen bg-white border-r fixed">
    <!-- code from snippet -->
</div>
<div class="w-16">
    <!-- content -->
</div>
```


I could think of other examples where maybe this kind of side-menu would be inside of a floating container or something that would

**Comment by markmead** [comment]
Hey @jessycormier did you mean to close this?
