### ISSUE TITLE
Provide a way to support RTL

### ISSUE THREAD

**Issue by i74ifa** [markmead/hyperui#134]
I'm trying to add a direction button to support RTL but I'm not good at react 
and I'm having problems with the proper way to activate this button
I want to click on it to add classes
as an example ```rtl:text-right```

![video](https://i74ifa.com/button-direction-on-hyperui.webp)

**Comment by markmead** [comment]
I'm not looking to add this feature. It would require a lot more classes to be written in the HTML that I'd wager 90% of developers will end up deleting. It wouldn't be too difficult to copy the components HTML and add the classes yourself.

**Comment by markmead** [comment]
Just a reminder to create an issue before working on something like this, I'd hate for anyone to waste time on something that isn't going to be added to HyperUI. 🚀

**Comment by i74ifa** [comment]
Yes, I saw that adding the feature required a lot of HTML files.
It's okay just try 👌🏻

**Comment by markmead** [comment]
What do you mean by?
> It's okay just try

**Comment by i74ifa** [comment]
Just added the button 😄

**Comment by markmead** [comment]
Sorry @i74ifa I don't know what you're talking about, this feature will **not** be added.
