### ISSUE TITLE
[BUG] Filter Component Radio Buttons

### ISSUE THREAD

**Issue by emorevival** [markmead/hyperui#139]
**Describe the bug**
Once you check a radio button, if you click it again nothing happens and even when clicking the "clear all" button the radio buttons still aren't being cleared

**To Reproduce**
1. Go to [the page for the filter component](https://www.hyperui.dev/components/application-ui/filters)
2. Click on "Undergraduate" to select it
3. Click on it again to clear it
4. Click on the "clear all" button
5. See error

**Expected behavior**
When clicking on a selected radio button, it gets unselected. When clicking on "clear all", all buttons (including radio buttons) get unselected.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Browser: Firefox
 - Version: 103.0.2

**Comment by markmead** [comment]
Yeah, the radio button is an issue, that should be an easy HTML change. Did you want to handle this?

However, the "Clear All" button is not something I'll be looking at. These components aren't interactive because how would I know how that functionality is being implemented in your use case?

**Comment by emorevival** [comment]
> Yeah, the radio button is an issue, that should be an easy HTML change. Did you want to handle this?

Sure, could be a good first PR? :) Good point about the "clear all" button, just looked odd cause the other buttons were being cleared

**Comment by HelloEdit** [comment]
Maybe this can help

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/reset

**Comment by markmead** [comment]
That's a great approach @HelloEdit! 

It works and doesn't require any assumptions on what developers are using, it's perfect, thanks for the suggestion!
