### ISSUE TITLE
Buttons: different sizes, active states, groups

### ISSUE THREAD

**Issue by adroste** [markmead/hyperui#14]
I just saw that you added / refined the button styles.
Here are some things I find would be nice to have:
* Different / smaller button sizes (like xs, s, m)
* Styled active states for visual feedback (just simple stuff like a one step darker / brighter color)
* Button-Groups

**Comment by markmead** [comment]
Hey @adroste thanks for the suggestions!

**Size Variants**

This is a simple change that can be done once the code has been copied, feels overkill to include it in HyperUI.

**Active States**

Great idea! I'll start looking into that.

**Button Groups**

I'll start looking into some nice designs and add the collection when I have some components.

---

I'll leave this open and keep you updated on when I make these additions/changes.

**Comment by markmead** [comment]
Hey @adroste

Just keeping you in the loop! I've added some basic active and focus states to the button components.

Next, I'll be looking at the button group collection.

**Comment by adroste** [comment]
Great addition. Looks nice and clean.

**Comment by markmead** [comment]
Added some button group components, more to come! 

Gonna close this now, thanks for the suggestions!
