### ISSUE TITLE
[REQUEST] Add Creator Link

### ISSUE THREAD

**Issue by GowthamRajendrann** [markmead/hyperui#150]
Link to the creator's GitHub profile or social profile will be a
![Screenshot 2022-09-14 220854](https://user-images.githubusercontent.com/94743096/190212928-f490e94e-4bfe-4dae-9b77-a10c7c6fd346.png)
 useful addition

**Comment by markmead** [comment]
This is something I've considered but I never settled on a UI. A few considerations are:

- What if the creator doesn't want to be shown?
- How useful is this information?
