### ISSUE TITLE
[REQUEST] 404 Templates

### ISSUE THREAD

**Issue by felixmacaspac** [markmead/hyperui#174]
I think a list of landing page templates is a great addition to this project, such as:
 
- Landing Page templates
- 404 Page templates

**Comment by markmead** [comment]
Great idea on the 404s, but I'm not sure about the landing pages, that feels like a lot of work, and a lot of the time they're very custom to the product/brand. What sort of ideas did you have for them?

**Comment by felixmacaspac** [comment]
I realized that the landing pages need a lot of work lol. But I think we can push thru with the 404 components/templates.

**Comment by markmead** [comment]
Sounds like a plan. 

Did you want to make a start on some 404s?

**Comment by felixmacaspac** [comment]
Sure thing, let me know if you've already created a category for it.

**Comment by markmead** [comment]
Just created a PR, it's all yours now. #178

**Comment by markmead** [comment]
Updated. I've merged that PR in so you can PR from the `main` branch. Hopefully, that is easier.

**Comment by felixmacaspac** [comment]
Sure thing, thank you!
