### ISSUE TITLE
Accessibility Improvements (Website)

### ISSUE THREAD

**Issue by markmead** [markmead/hyperui#185]
It's 100/100 on Lighthouse but there's definitely more that can be done.

**Comment by jyotika6221** [comment]
Please assign me this task.

**Comment by markmead** [comment]
It will remain assigned to me, but you are welcome to work on it @jyotika6221

**Comment by jyotika6221** [comment]
ok fine, but will it be considered a valid pr?

**Comment by markmead** [comment]
Yes, as Hacktoberfest tracks PRs.
