### ISSUE TITLE
Accessibility Improvements (Components)

### ISSUE THREAD

**Issue by markmead** [markmead/hyperui#186]
Most components should be OK, but there are likely to be improvements.

**Comment by irham9494h** [comment]
Hi @markmead 
May you allow me to work on this issue?, if the answer is "yes" which components need improvement? Thank you

**Comment by markmead** [comment]
Hi, @irham9494h I'm happy for you to work on this. Thanks for your interest!

There's no strict "this component needs looking at", it's more of a general review to improve accessibility.

Please don't feel like you need to do every component, just do the ones you are comfortable with 🎉

**Comment by jyotika6221** [comment]
Please assign me this task, it can be my 1st pr for hacktoberfest.

**Comment by markmead** [comment]
Happy for you to work on @jyotika6221 but there's no need to change the assignee.

**Comment by dianaberna** [comment]
hi! I am a frontend dev and accessibility consultant, could I also help test accessibility? @markmead

**Comment by markmead** [comment]
Hey, @dianaberna of course! 🎉 

Feel free to do as much/little as you feel like. It's an open issue for anyone to come in and make improvements.

**Comment by markmead** [comment]
I'm going to close this issue as I'm no longer getting relevant errors back from pa11y or aXe. 

However, PRs are still welcome to improve accessibility.
