### ISSUE TITLE
"How to Contribute to HyperUI"  link is not working[BUG] ...

### ISSUE THREAD

**Issue by adityaacse** [markmead/hyperui#191]
**Describe the bug**
https://github.com/markmead/hyperui/blob/main/src/data/posts/hacktoberfest-2022.mdx
The above page has a link "How to Contribute to HyperUI" which is throwing 404 error.

**Expected behavior**
"How to Contribute to HyperUI" page must be opened.

**Screenshots**
![404 error](https://user-images.githubusercontent.com/19973475/194857958-9e91d039-17ef-4d5d-bb5c-7af5f7eca701.png)

**Desktop (please complete the following information):**

- OS: Window 10
- Browser: Chrome

**Comment by adityaacse** [comment]
I am interested in fixing this issue, please let me know the correct URL.

**Comment by markmead** [comment]
This is working fine.
