### ISSUE TITLE
[BUG] Broken Category Slug in Header Search

### ISSUE THREAD

**Issue by sugaya24** [markmead/hyperui#204]
**Describe the bug**
Links in HeaderSearch are broken as it contains object in the links.

**To Reproduce**

1. Click on a HeaderSerach
2. Click on a link to a category

**Expected behavior**
The correct page is displayed.

**Screenshots**
<img width="899" alt="Screen Shot 2022-10-24 at 9 38 03 PM" src="https://user-images.githubusercontent.com/13996983/197527263-441ee9e7-02a3-4efa-baeb-2e196f6931ab.png">

**Comment by markmead** [comment]
Oops, thanks for reporting this. I'll get it fixed.

**Comment by markmead** [comment]
Should be fixed now, thanks for the help! 🎉
