### ISSUE TITLE
Cards: Card 23 Missing Closing Tag

### ISSUE THREAD

**Issue by KalynDavis** [markmead/hyperui#21]
**Bug Description**
The card component is missing the appropriate closing `</dt>` at `components/cards/23.html:26`.

P.S. Thanks for this amazing kit!

**Comment by KalynDavis** [comment]
I added a PR for this issue #22 to fix this issue :)

**Comment by markmead** [comment]
Ooops, my bad! 

Thanks for the PR @KalynDavis it's now merged! 🥳
