### ISSUE TITLE
[GOAL] Pass 100+ Ecommerce Components

### ISSUE THREAD

**Issue by markmead** [markmead/hyperui#212]
The aim is to pass 100+ ecommerce components by December. As can be seen here https://www.hyperui.dev/api/stats the ecommerce component offering is lacking.

I'll use this issue as a dumping ground for ideas and progress tracking.

- [x] Product Cards (Update)
- [x] Product Cards (New)
- [x] Collection Cards (New)
- [x] Product Collections (Update)
- [x] Carts (Update)
- [ ] Carts (New)
- [x] Checkouts (Update)
- [x] Quantity Inputs

**Comment by markmead** [comment]
OK, so it's looking like 100+ won't be reached by December, but 75+ could/should be doable.

**Comment by markmead** [comment]
I've merged in #213 which added 51 components, this bring the number of ecommerce components to... 🥁

69. 😶

**Comment by ishaanbedi** [comment]
Hi @markmead !
75+ still looks doable. 
I'd love to contribute to the same. 
If I'm reading the issue right, the project is lacking components for the cart in the e-commerce section. 
But what's with Carts (Update) and Carts (New)? What is it about?
Once I have a clear vision of this, I'd start working on designing and developing new components.

**Comment by markmead** [comment]
Hi @ishaanbedi 👋

It's not doable as we're now **in December** and the goal was **by December**.

It was lacking ecommerce components in general but that has been improved. I've used the checkboxes to track what needs to be done, therefore, it is showing that new cart components have not been added.

**Comment by ishaanbedi** [comment]
> @markmead: It's not doable as we're now in December and the goal was by December.

Ah, my bad! I skim-read it to be by end of December, so sorry for that.
By the way, I've designed a `full screen cart` component, but due to the implication of styling rule `container: flex justify-center p-8` in `ecommerce-carts.mdx`, I'm unable to make it stretch throughout the component box. 

Can you please help me with it so that I can proceed with the PR for the same?
Should I open an issue/discussion for it so future contributors can also benefit from there?

**Comment by markmead** [comment]
Hi @ishaanbedi 👋

Not a problem! That's easy to do, if you look at this - https://raw.githubusercontent.com/markmead/hyperui/main/src/data/components/marketing-popups.mdx

You can see that the `container` can be overridden at a component level. I usually do `container: relative` when it needs to be full width.

**Comment by markmead** [comment]
It needs to be a PR if you want me to review it @ishaanbedi
