### ISSUE TITLE
[FEATURE] Dark Mode Footer Variants

### ISSUE THREAD

**Issue by rubydesign** [markmead/hyperui#215]
Well, first off all i have to say thanks, great work.
I am on rails and wanted a clean looking "framework" without npm, and this fits the bill SO well.
I would not mind paying some if you had a button for it. (coffee/paypal)
Anyway, i will start probably several sites with this, writing a cms around the elements. Meaning i will probably be able to contribute in the future, now i am just starting with tailwind.

**Is your feature request related to a problem? Please describe.**
The first footer is great, but only in dark

**Describe the solution you'd like**
I need the footer in white

**Describe alternatives you've considered**
Obviously using another as place holder for now

**Additional context**
I've seen many other components where one can choose dark/white and that would be great for the first one too.

**Comment by markmead** [comment]
Hey, @rubydesign thanks for the kind words. I'll look at getting some footer variants created.

**Comment by markmead** [comment]
Here's the first footer that you referenced - https://hyperui-git-update-footer-variants-markmead.vercel.app/components/marketing/footers#component-1

**Comment by rubydesign** [comment]
Thanks a lot. Looks great, copied!
Do you want these mini inputs,don't want to get on anybodies nerves?
Since i am learning tw i am starting to make changes.

Ideally i  would comment on a discord or something.

**Comment by markmead** [comment]
GitHub issues are the perfect place for that. It's not going to annoy anyone.
