### ISSUE TITLE
[FEATURE] Global Dark Mode Toggle

### ISSUE THREAD

**Issue by rohitbulusu** [markmead/hyperui#217]
**Is your feature request related to a problem? Please describe.**
My feature request isn't related to a problem but more of an additional feature/functionality. I think it would be really cool if the site in general had a dark mode toggle. Either one that works globally across the entire site or across components individually.

**Describe the solution you'd like**
I would like to contribute if possible by adding a global dark mode toggle at the top right of the site, which looks for any tailwind classes marked with `dark:` and then if that goes well add dark mode variants to some components.. 

**Describe alternatives you've considered**
I was thinking of either Global Dark mode, which can perhaps be placed at the top right of the website, built with a nice slider, which applies it globally across the whole site and also each component, or at a component level where each one can have a dark mode toggle, but would like to know your thoughts on this.

**Additional context**

**Comment by markmead** [comment]
Hi, @rohitbulusu thanks for your thoughts on this. Sadly, this is unlikely to make it into HyperUI at the moment due to not all components having a dark mode variant which will cause confusion for users.
