### ISSUE TITLE
[REQUEST] Cards with Full Image

### ISSUE THREAD

**Issue by rubydesign** [markmead/hyperui#219]
**Describe the bug**
https://www.hyperui.dev/components/ecommerce/cards

If this is now a feature request or bug report i don't know.

As a feature request i would say more cards / hero sections with full picture

As a bug report: that last card does not fit in with the style of the rest (also the first to some degree)

I would say it's the red

**Expected behavior**

I would expect all the elements to look harmonious together. Otherwise you would need to introduce the concept of themes, and i don't think there are enough components for that.

**Additional context**

I changed the red to a mild orange (less harsh). 
And made a margin around the text box, so the box does not look so squeezed in the corner, more integrated.
Also changed the transition to a zoom.
I can try to do a pr if you want

**Comment by markmead** [comment]
Hi @rubydesign, if you look at #213 you will notice these components have been removed. 

However, this isn't feedback that I'm interested in and it appears, from the following comments, you aren't seeing the value of HyperUI.

> I would expect all the elements to look harmonious together

Why? 

This is a component library full of ideas that you can use, or take inspiration from and build something. There is nothing that states all components in HyperUI work together.

> That last card does not fit in with the style of the rest

Why should it? 

This is a component idea dumping ground, I have an idea, I build it and if it works it is released. If you see something that you don't like, copy the component and change it.

**Comment by markmead** [comment]
Oh and "I changed the red to a mild orange (less harsh)" is how HyperUI should be used, but making an issue/PR to "correct" the component for everyone is not how it should be used.

What you think is correct, isn't correct for everyone.

**Comment by rubydesign** [comment]
Well, i see from the strong reaction that i have upset/offended you. I am very sorry, that was not my intent at all. 
I am obviously not a designer more developer, and as such greatly see the benefit and am grateful.
But i seem to misunderstood the intent and previous comment, so I'll just shut up and be grateful in silence :-)

**Comment by markmead** [comment]
I'm not upset or offended, please don't think you've caused anything like that. We're all good.

It's more frustrating. 

I'm all for the components being edited by developers, I don't have any "they must be used this way" feelings toward them. If you want to make a color change, go for it! However, that isn't something I'm going to change for everyone unless it was an a11y concern.

If feedback about components is stuff like "I think this should have a list so more content can be added" then that can be looked at as that's something that might enhance the component for everyone.
