### ISSUE TITLE
[REQUEST] Navigation Between Components

### ISSUE THREAD

**Issue by EvodiaAut** [markmead/hyperui#228]
**First of all many special thanks for this great work!**
**So many fantastic components really amazing!**

My suggestion for a faster navigation between the components is a side menu with groups like carts and inner with Popup, #Popup (Interactive), ...

A really good solution has https://flowrift.com or simplify https://mambaui.com.

**Comment by markmead** [comment]
Hi, @EvodiaAut thanks for the suggestion. 

I'll look into this.

**Comment by EvodiaAut** [comment]
Thank you @markmead.

It's a good start 🚀 someday as sticky sidebar and its perfect 🤩.
