### ISSUE TITLE
[QUESTION] Svelte Framework Library

### ISSUE THREAD

**Issue by sjcobb2022** [markmead/hyperui#264]
Hi there, 

This isn't much of a request, more asking approval more than anything else.

I absolutely love everything that you've done here. I am currently working on a personal project in svelte and I would love to write some simple svelte wrappers around your components.

I would love to hear your thoughts!

**Comment by markmead** [comment]
Sounds great, I'm all for that! @sjcobb2022

Shoot me over a link to the project when it's up and running, would love to take a look! 

Thanks for asking 🙌
