### ISSUE TITLE
[FEATURE] Add JSX Copy Functionality

### ISSUE THREAD

**Issue by alancpazetto** [markmead/hyperui#271]
**Is your feature request related to a problem? Please describe.**
No 🙏 

**Describe the solution you'd like**
Add support to copy HTML code as JSX code.

**Describe alternatives you've considered**
Add aa setting to toggle use JSX or not and when click copy button, should convert to JSX.

**Additional context**
No context

**Comment by markmead** [comment]
This isn't as straight forward as you think, it isn't just `class` to `className` you have to worry about.
