### ISSUE TITLE
[BUG] Filters & Sorting Button Broken

### ISSUE THREAD

**Issue by Maaz0313** [markmead/hyperui#274]
**Describe the bug**
In 'Medium', 'Small' and 'Mobile' view, the 'Filters & Sorting' button is not opening like a dropdown.

**To Reproduce**

1. Go to 'https://www.hyperui.dev/components/ecommerce/product-collections#component-6'
2. Click on 'Medium', 'Small' and 'Mobile' icons one-by-one and click on 'Filters & Sorting' button to see the error. It should open like a dropdown but it's not.

**Expected behavior**
'Filters & Sorting' button should open like a dropdown to show the filters but it's not.

**Comment by markmead** [comment]
There's no dropdown as it's not an interactive (Alpine JS) variant, therefore, it's on you to make it interactive.

I'll look into making an Alpine JS variant.
