### ISSUE TITLE
New Component Request: Tables

### ISSUE THREAD

**Issue by heddendorp** [markmead/hyperui#28]
**Tables**

Styled tables to display data

**Examples of Component**
https://tailwindui.com/components/application-ui/lists/tables
https://material.angular.io/components/table/examples
https://material.io/components/data-tables#usage
https://getbootstrap.com/docs/5.1/content/tables/

**Comment by markmead** [comment]
Hey, @heddendorp tables are on the radar, but I won't be using Tailwind UI as examples.

**Comment by heddendorp** [comment]
> Hey, @heddendorp tables are on the radar, but I won't be using Tailwind UI as examples.

Good to hear
I tried to add some more table reference.

**Comment by markmead** [comment]
Perfect, thank you! I'm trying to avoid anything too similar to Tailwind UI for obvious reasons, aha!

**Comment by markmead** [comment]
Created some basic tables, will continue to add more - https://hyperui.dev/components/tables
