### ISSUE TITLE
Improving overall frontend

### ISSUE THREAD

**Issue by abhinav2712** [markmead/hyperui#286]
**Is your feature request related to a problem? Please describe.**
Its not actually a major problem but the website looks dull and quite basic

**Describe the solution you'd like**
Allow me to apply my UI skills and improve the frontend

**Comment by markmead** [comment]
Sure thing. I look forward to your PR. Good luck!

**Comment by abhinav2712** [comment]
@markmead Assign me this issue so that i can start working without any hasstle
