### ISSUE TITLE
Customize issue template

### ISSUE THREAD

**Issue by Aniket1026** [markmead/hyperui#291]
The issue template we had currently splits the issue only in two categories
* Bug
* Feature request

However there may be other issues that do not come under these two categories such as 
* Documentation issue
* Any kind of security vulnerabilities
* May be any question or general doubt regarding the project
* Or???? may be if you want an we can have an "**other**" category for those which doesn't comes under any other type

Would love to know your views on how do you wish to customize it.
If everything is fine regarding the issue I'd love to work on it
Thank you 🙂

**Comment by markmead** [comment]
There's a button that says "Create a blank issue" that covers anything that doesn't have a template.
