### ISSUE TITLE
[ENHANCEMENT] More (Marketing) Stat Components

### ISSUE THREAD

**Issue by AliSinaYOusofi** [markmead/hyperui#301]
**Is your feature request related to a problem? Please describe.**
Show the stats of a website is crucial. And hyperui has only one stats component i want to add another one or even more.

**Describe the solution you'd like**
I want hyperui users to have more stats component and since we have just one stats component it is a good idea to have more of this component.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
I haven't started working on it yet. If you think it's a good idea to have multiple stats component then I'm ready to start.

**Comment by markmead** [comment]
Sounds good @AliSinaYOusofi Go for it! 🥳

**Comment by ExactlyRahul** [comment]
Yeah, go for it. Maybe we can get some cool ideas from dribble.

**Comment by markmead** [comment]
Welcome to make a PR as well @ExactlyRahul, Dribbble is a great source of inspiration! 🚀

**Comment by ExactlyRahul** [comment]
> Welcome to make a PR as well @ExactlyRahul, Dribbble is a great source of inspiration! 🚀

Thanks, I can do I think, but I never did collaboration. I will learn something new so I'll try. Let's see how it goes :D
