### ISSUE TITLE
[ENHANCEMENT] Blog Card with Background

### ISSUE THREAD

**Issue by diomed** [markmead/hyperui#326]
Hi Mark

I wonder if you could make a blog card example that has text in picture, just like last example here in banners: 
https://www.hyperui.dev/components/marketing/banners

**Comment by markmead** [comment]
Hi @diomed 👋 

Do you have any examples?

**Comment by markmead** [comment]
Ah OK, I understand. Did you want to take a look at making a PR for it?

**Comment by diomed** [comment]
no

**Comment by markmead** [comment]
No problem!

**Comment by diomed** [comment]
Thank you
