### ISSUE TITLE
[Drawer] - Display overlay area at any side of the screen

### ISSUE THREAD

**Issue by usman-faisal** [markmead/hyperui#334]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
implement a drawer like GitHub's side panel

**Describe alternatives you've considered**
None

**Additional context**

**Comment by markmead** [comment]
https://www.hyperui.dev/components/application-ui/side-menu

I'm sure you can adjust one of those to look like GitHub 🎉
