### ISSUE TITLE
[ENHANCEMENT] - Pricing Section Components

### ISSUE THREAD

**Issue by usman-faisal** [markmead/hyperui#335]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
a section for showing pricing plans.

**Describe alternatives you've considered**
none

**Additional context**
![image](https://github.com/markmead/hyperui/assets/118989113/ef5c2561-83ba-4d65-8823-6c38281aea92)

**Comment by markmead** [comment]
Nice suggestion @usman-faisal I'll take a look, thanks!

**Comment by usman-faisal** [comment]
okay great! can I be assigned to this task?
