### ISSUE TITLE
Component "Sidebar (Left - Expandable)" has a missing `>` in the HTML

### ISSUE THREAD

**Issue by hussainmahmood** [markmead/hyperui#367]
![image](https://github.com/markmead/hyperui/assets/24608542/52520592-5eab-4ea0-aa90-da74920b6d3f)

last class has lg:[&:has(*:first-child:hover)]:grid-cols-[160px_1fr] while it should have been lg:[&:has(>*:first-child:hover)]:grid-cols-[160px_1fr].

Thank you.

**Comment by markmead** [comment]
Thanks @hussainmahmood, feel free to make a PR.
