### ISSUE TITLE
Adding a Table Design Component

### ISSUE THREAD

**Issue by mdjamilkashemporosh** [markmead/hyperui#369]
Hello,
I'm really impressed with the project. I'd like to contribute by adding a new table design component to the project, which I believe would be a valuable addition for users.

Before I start working on it, I wanted to seek guidance on the best way to proceed. Could you please provide me with some insights or guidelines on how to add new components to the project? Any advice or specific requirements you have for contributions would be greatly appreciated.

I'm eager to contribute and ensure that the table design aligns with the project's standards and goals. Your guidance will be invaluable in helping me get started on the right track.

Thank you for your time, and I'm looking forward to your response.

Best regards,
MD Jamil 

DEMO:: 
![pika-1694163402030-1x](https://github.com/markmead/hyperui/assets/50365984/311ecbbb-21db-4489-9f9c-d4f3a982c71c)

**Comment by markmead** [comment]
Hey there @mdjamilkashemporosh,

I have a blog post on the site about how you can contribute to the project, take a look - https://www.hyperui.dev/blog/how-to-contribute, if you have any further questions then please let me know.
