### ISSUE TITLE
How to use components

### ISSUE THREAD

**Issue by Aniket1026** [markmead/hyperui#376]
This issue is more likely a question regarding how to use HyperUI components in my projects?
Is there any pre-requisites apart from setting up the tailwind configuration? 
Because i tried using the component and it looks different on my local when i tried using them

I tried using the alert component which looks like this

<img width="923" alt="hyperUI-alert" src="https://github.com/markmead/hyperui/assets/92184189/35ae7c3d-cee7-4795-82f2-a2f71eb43594">

but after copying the component on my local it appeared like this which is too big to fit the screen
I copied the jsx version into my jsx file. Also i'm using react18 on my windows 10 device

<img width="920" alt="my-alert" src="https://github.com/markmead/hyperui/assets/92184189/cdedaceb-939f-4807-b9ee-48541618fee2">

I don't know if something is missing from my side, please let me know
Thank you ✨

**Comment by Aniket1026** [comment]
yes, i was aware of the fact that this requires tailwind. But yes i fixed it, the issue was with my tail config file

**Comment by markmead** [comment]
Sorry @Aniket1026, it really looked like you didn't have Tailwind CSS. What was wrong with the config?

**Comment by Aniket1026** [comment]
I had tailwind installed but the issue was with my tailwind.config file which i fixed myself 
Sorry for the inconvenience @markmead

**Comment by markmead** [comment]
No you're all good @Aniket1026! Sorry for the bluntness in my first response.

**Comment by Aniket1026** [comment]
It was just mutual confusion nothing to be sorry 😊
