### ISSUE TITLE
This is a kind suggestion from this fan of your project, I love it!

### ISSUE THREAD

**Issue by ivanosquis10** [markmead/hyperui#377]
Hello dear friends, I hope you're feeling well. This is a small proposal for the "grid" section, I feel that the color that highlights the grid is very light and it's a little difficult to visualize, at least for me it's a lot (I'm a little blind too).

My idea would be to place a **darker color**, that is more noticeable and that stands out to be able to understand very clearly what style is the grid :)

That's my proposal, I love your project, it's one of the best on the internet, I use it a lot, I love you guys!

**Comment by markmead** [comment]
Thanks for the kind words @ivanosquis10!

Your suggestion makes sense to me, I'll get that updated.
