### ISSUE TITLE
Header not opening with toggle on mobile

### ISSUE THREAD

**Issue by ParsaJR** [markmead/hyperui#378]
Why does the header not open in mobile with toggle? is it correct ? Was mobile toggle not supposed to be created by hyper ui at all? It was strange to me . 
(marketing/headers)

![Screenshot 2023-09-21 205237](https://github.com/markmead/hyperui/assets/98831377/5c7ebf23-2ee6-42c5-b676-96ae071469ad)
![Screenshot 2023-09-21 205620](https://github.com/markmead/hyperui/assets/98831377/ef04bacf-94e7-4120-99b5-2669c1c47e8d)

**Comment by markmead** [comment]
No, there's no menu for the header components as it's a bit of a rabbit hole of variations. However, I'll take a look.
