### ISSUE TITLE
Add some more table components

### ISSUE THREAD

**Issue by mdjamilkashemporosh** [markmead/hyperui#380]
I propose the addition of a new table component to enhance the existing options available. While there are already some table components available, I strongly believe that my addition would greatly benefit the hyper UI.

**Preview::** 
![image](https://github.com/markmead/hyperui/assets/50365984/c9805528-f6e7-4269-bbd9-d2f2800ea0b4)

**Comment by mdjamilkashemporosh** [comment]
![image](https://github.com/markmead/hyperui/assets/50365984/cfed511f-4def-43b9-bad5-90b7bd936445)

**Comment by mdjamilkashemporosh** [comment]
![image](https://github.com/markmead/hyperui/assets/50365984/ce8dcec3-3607-4e8f-b686-a622d4aa2eea)

**Comment by mdjamilkashemporosh** [comment]
![image](https://github.com/markmead/hyperui/assets/50365984/f725fe65-767a-4b0b-a56d-fe344d43efcd)

**Comment by markmead** [comment]
Hey @mdjamilkashemporosh,

I'm happy for you to look at a table component with pagination. However, I feel the other examples are just variations of table components with slightly different approaches to the borders, none of which particularly make sense.

**Comment by markmead** [comment]
I think start with the last one for now.

**Comment by mdjamilkashemporosh** [comment]
@markmead Got it! Thanks

**Comment by KunjMaheshwari** [comment]
Hey @mdjamilkashemporosh,

I'm happy for you to look at a table component with pagination. However, I feel the other examples are just variations of table components with slightly different approaches to the borders, none of which particularly make sense.

If you do create the component can you please use an existing table and pagination component as your base.

**Comment by mdjamilkashemporosh** [comment]
Hey @KunjMaheshwari,
Thank you for sharing the information.

**Comment by beandnam** [comment]
Hey @KunjMaheshwari,
Thank you for sharing the information.

**Comment by markmead** [comment]
> Hey @KunjMaheshwari, Thank you for sharing the information.

It was just a copy of my reply, no idea why they did that 🤷‍♀️
