### ISSUE TITLE
Nav bar must be little broader 

### ISSUE THREAD

**Issue by P-Potdar** [markmead/hyperui#385]
<img width="456" alt="Screenshot 2023-10-07 at 2 55 03 PM" src="https://github.com/markmead/hyperui/assets/109173669/6d6cc430-d62f-4c22-ae58-29539b9f192c">
I would fix it

**Comment by markmead** [comment]
I disagree and saying something "must be" is not the approach I'd take when sharing an opinion.

Please put more effort into your issues, it's starting to feel like Hacktoberfest spam.
