### ISSUE TITLE
Add a custom error page

### ISSUE THREAD

**Issue by ArnavK-09** [markmead/hyperui#386]
**To Reproduce**

1. Go to '/404'

**Expected behavior**
Should inform the user if the page doesn't exist 

**Screenshots**
![Screenshot_2023-10-07-23-24-10-52_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/markmead/hyperui/assets/69188140/c2f78107-b326-4807-b66d-6ef6a29b44d8)

**Smartphone (please complete the following information):**

- Device: Oppo
- OS: Android 13
- Browser Chrome

**Comment by markmead** [comment]
Error pages are handled by Next but a custom one would be cool.
