### ISSUE TITLE
Improvement in UI of footer

### ISSUE THREAD

**Issue by Naina047** [markmead/hyperui#388]
**Describe the bug**
I would like to improve the footer in the website. as it is not differentiating from rest of the website.
Please assign me under Hacktoberfest'23.

**Screenshots**
![Screenshot 2023-10-08 113218](https://github.com/markmead/hyperui/assets/96466577/60d08aaa-a1ca-4ea2-8028-bd5ba8be0488)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome

**Comment by shivamsinghcse** [comment]
i want to work on this issue can you please assign me this issue.

**Comment by markmead** [comment]
Nope, it doesn't need changing.
