### ISSUE TITLE
Add some more pricing components

### ISSUE THREAD

**Issue by mdjamilkashemporosh** [markmead/hyperui#389]
I would like to add a new pricing component to enhance the existing options available. While one pricing component is already available, I firmly believe my addition would greatly benefit the hyper UI.

Preview::

![image](https://github.com/markmead/hyperui/assets/50365984/e1b30320-dd22-42e5-990b-121ad30dd5da)

**Comment by markmead** [comment]
Sounds good, PR welcome!

**Comment by shalini0002** [comment]
please assign this to me
