### ISSUE TITLE
Add some more dynamic input components

### ISSUE THREAD

**Issue by mdjamilkashemporosh** [markmead/hyperui#390]
I would like to add a new dynamic input component to enhance the existing options available. While some input components are already available, I firmly believe my addition would greatly benefit the hyper UI.

Preview::

before typing:: 

![image](https://github.com/markmead/hyperui/assets/50365984/08378322-f331-4e86-95a1-90cf52e2d65f)
![image](https://github.com/markmead/hyperui/assets/50365984/0ab2c2da-edad-4e95-a966-8756361939c8)

during typing ( on focus ) 

![image](https://github.com/markmead/hyperui/assets/50365984/b96d2cad-3434-41e2-9d27-aa8679ad460a)
![image](https://github.com/markmead/hyperui/assets/50365984/5ef4e08a-bdcb-4682-982c-5962d991b292)
![image](https://github.com/markmead/hyperui/assets/50365984/f7a4586a-83e9-4852-93ee-b6a919942a52)

**Comment by markmead** [comment]
Sounds good, PR welcome!
