### ISSUE TITLE
Improve HyperUI README

### ISSUE THREAD

**Issue by ToobaJamal** [markmead/hyperui#394]
The current README gives an overview of HyperUI but it lacks necessary details like:
1. Getting started: Describes how to start using HyperUI in a project. Since it doesn't require installation, it section is going to be interesting.
2. Usage: How to use HyperUI components including use cases, screenshots/ GIFs.
3. Components: List of components available in HyperUI including links.
4. Contributing: How developers can contribute to this project.
5. Licence.

I would love to work on this if you approve.

**Comment by mdjamilkashemporosh** [comment]
hey @ToobaJamal, Here is a blog post that provides detailed guidance on how to contribute to HyperUI: [How to Contribute to HyperUI](https://www.hyperui.dev/blog/how-to-contribute). 

HyperUI is licensed under the MIT license. To use it, visit [HyperUI](https://www.hyperui.dev/), choose the components or features you want to use, copy the code, and integrate it into your project.

**Comment by markmead** [comment]
Hey @ToobaJamal README updates sound good!

There's a blog post on the website that details how you can contribute to the project, please link to that.
