### ISSUE TITLE
Add a profile settings form

### ISSUE THREAD

**Issue by NDOY3M4N** [markmead/hyperui#395]
I would like to add a **profile settings form** to the [forms](https://www.hyperui.dev/components/marketing/forms) layout.

**Comment by markmead** [comment]
OK dokie!

**Comment by AnshuWorld** [comment]
I want to contribute here please give me permission

**Comment by markmead** [comment]
> I want to contribute here please give me permission

No, @NDOY3M4N is already working on it.
