### ISSUE TITLE
Remove tap highlight on mobile devices for toggles

### ISSUE THREAD

**Issue by NDOY3M4N** [markmead/hyperui#399]
**Describe the bug**
On mobile devices, when pressing the toggle component, there is tap highlight.

**To Reproduce**

1. Go to **Toggle component**
2. Click on any toggle while being on mobile (or in the browser device emulation)
3. There is a highlight when pressing the toggle

**Expected behavior**
Like in desktop / tablet, I think there shouldn't be a highlight when pressing the toggle on mobile devices

**Screenshots**

https://github.com/markmead/hyperui/assets/46305144/605f3821-e77b-4709-b50c-363068869354

**Smartphone (please complete the following information):**

- Device: iPhone XR
- OS: iOS 17
- Browser safari
- Version 17

**Comment by NDOY3M4N** [comment]
`-webkit-tap-highlight-color` can help solve this issue

**Comment by markmead** [comment]
Sounds like a good change to me!
