### ISSUE TITLE
Add a Back To Top Button

### ISSUE THREAD

**Issue by neha3423** [markmead/hyperui#403]
**Is your feature request related to a problem? Please describe.**

Sometimes, it is not so easy to scroll back to top of the webpage, especially when it is a long page. By adding a "Back to top" button would make the navigation much easier.

**Describe the solution you'd like**

Adding a "Back To Top" button, located in the lower right corner of the screen, when clicked it would scroll back to the top of the page.

**Additional context**

![img](https://github.com/markmead/hyperui/assets/129765919/a95b6fa2-4e41-44a5-a468-bb0921e09855)

This way the "Back To Top" button can be added to easily scroll back to the top.

**Comment by neha3423** [comment]
I would like to work on this enhancement.

**Comment by Souradeephazra123** [comment]
I also like to work on it

**Comment by chinmay7016** [comment]
It would be great if you assign me this

**Comment by markmead** [comment]
This isn't needed.
