### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by milan-codes** [markmead/hyperui#407]
**Describe the bug**
Cannot browse any components on [hyperui.dev](https://www.hyperui.dev/) as the server throws an internal server error, with the following message: ```INTERNAL_INVALID_FUNCTION_REGION```

**To Reproduce**
Go to [hyperui.dev](https://www.hyperui.dev/), and try browsing any categories.

**Expected behavior**
Browsing components on [hyperui.dev](https://www.hyperui.dev/) should be available, instead of GitHub

**Screenshots**
<img width="1431" alt="Screenshot 2023-10-17 at 12 30 19" src="https://github.com/markmead/hyperui/assets/36796352/30b89027-f5b4-42a7-8b53-3726cdc1a2eb">

**Comment by Koffer0-0** [comment]
Hey, thank you that made an issue about this error, I have stucked with this 500 error, and had not idea how to contact with the creator. I hope this issue will be solved, because I am using this UI lib. Thank you!

**Comment by GeorgeFlorian** [comment]
I am also experiencing this issue.

**Comment by markmead** [comment]
Sorry about that, looks like something broke on Vercel with the recent deploy. Should be OK now! 🤞 

Thanks for reporting!
