### ISSUE TITLE
I would like to create a modal new collection

### ISSUE THREAD

**Issue by mahendrameghwal** [markmead/hyperui#408]
**Is your feature request related to a problem? Please describe.**
No this is not related to any problem but many of user who are  using **Tailwind css ** for those people might be help to get easy to intrigrate modal component on their future project

**Describe the solution you'd like**
Modals are often used to direct users' attention to an important action or piece of information on a website or application. The purpose of modals If you need visitors to focus on something simple, a modal window is one of the most effective means to do this.

**Describe alternatives you've considered**
No ,i don't consider any alternatives 

**Additional context**
the modal will be look like this 💯 
![Modals](https://cdn.dribbble.com/userupload/4455147/file/original-06d91733d2bed721beaf9170307eb139.png?resize=1200x900 "Modals")

**Comment by mahendrameghwal** [comment]
can i start work on this

**Comment by markmead** [comment]
Sounds good to me! Best to create one component at first, get that reviewed and then create some more based on that.

**Comment by mahendrameghwal** [comment]
Ok when I have time sure I will create

**Comment by hacker-4-good** [comment]
Hello @mahendrameghwal can I help you in creating component, as I am learning ReactJS. So seems interesting to contribute in open source. If yes, we can have further conversations.

**Comment by mahendrameghwal** [comment]
sure

**Comment by mahendrameghwal** [comment]
sure

**Comment by markmead** [comment]
> Hello @mahendrameghwal can I help you in creating component, as I am learning ReactJS. So seems interesting to contribute in open source. If yes, we can have further conversations.

It's worth noting that none of the Tailwind CSS components use React, it's all just HTML.

**Comment by hacker-4-good** [comment]
Ok, its just mean to share functional component return (html code)
