### ISSUE TITLE
A Dark Color Scheme

### ISSUE THREAD

**Issue by Michael-Obele** [markmead/hyperui#414]
**Is your feature request related to a problem? Please describe.**
Yes, the problem is that the website currently does not have a dark mode option, which can be frustrating for users who prefer a darker color scheme, especially at night.

**Describe the solution you'd like**
I would like the website to have a dark mode option that users can toggle on and off. This would make the website more accessible and user-friendly for those who prefer darker color schemes.

**Describe alternatives you've considered**
One alternative could be to use browser extensions or third-party tools to force a dark mode on the website, but this may not always work well and could lead to a subpar user experience.

**Additional context**
Adding a dark mode option could improve user experience and make the website more inclusive for those who prefer darker color schemes. It could also potentially reduce eye strain for some users.

**Comment by Michael-Obele** [comment]
I would love to work on this if possible.

**Comment by markmead** [comment]
Had this before but removed it. Not every website needs a dark mode.
