### ISSUE TITLE
I would like to work on a new 'Avatars' section

### ISSUE THREAD

**Issue by prajjwalyd** [markmead/hyperui#416]
Figma preview:
![image](https://github.com/markmead/hyperui/assets/111794524/7e3becbb-7e45-4ff7-95c3-75bdb6e5b9e4)

**Comment by markmead** [comment]
Thanks @prajjwalyd but I'm not looking to add these components.

**Comment by prajjwalyd** [comment]
Alright... is there any other component that I can work on? @markmead
