### ISSUE TITLE
New multi column layout component

### ISSUE THREAD

**Issue by KushalGhosh9899** [markmead/hyperui#418]
**Is your feature request related to a problem? Please describe.**
No, this isn't related to any problem rather this will be a **new component** that will help users design dashboards or accomplish many UI-related tasks.

**Describe the solution you'd like**
 I want to add a new component similar to the image(attached below) [official tailwind CSS component reference](https://tailwindui.com/components/application-ui/application-shells/multi-column).

**Describe alternatives you've considered**
No, I didn't consider any alternatives.

**Additional context**
The component will be similar to this.
![image](https://github.com/markmead/hyperui/assets/25982821/dbecfeea-63ad-4dd9-938c-218e69734a3e)
Note - This above component will come under **Side menu components** ([page link](https://www.hyperui.dev/components/application-ui/side-menu)) and

Official Component -
![image](https://github.com/markmead/hyperui/assets/25982821/277e9d73-d07b-48f0-b575-d60256a6bf85)

**Comment by KushalGhosh9899** [comment]
May I work on this? I'll follow the stylings of HyperUI's tailwind component

**Comment by markmead** [comment]
Hi @KushalGhosh9899, happy for you to take a look, be good to create the new component from the the existing HyperUI component(s) and just adjust it to support multi column layout.

**Comment by KushalGhosh9899** [comment]
Sure, will do that.
