### ISSUE TITLE
[BUG] Optimise transition classes in HyperUI components for enhanced CSS performance

### ISSUE THREAD

**Issue by techwithshubh** [markmead/hyperui#421]
Hello HyperUI maintainers,

I hope this message finds you well. While reviewing the HyperUI codebase, I've noticed that certain components utilise generic `transition` class for styling. To enhance the performance, especially when working with Tailwind CSS, I suggest narrowing down the usage of `transition` classes to more specific ones such as `transition-colors` or `transition-opacity` or custom.

Example:
https://www.hyperui.dev/components/application-ui/headers (`transition` class is used in button where only background colour property is changed on hover)

By making this adjustment, we can significantly improve the efficiency of these components, as it allows for more targeted and optimised styling, reducing unnecessary computations and enhancing overall performance.

I propose revisiting and refactoring the affected components to use the more narrowed down transition classes and **I would like to contribute on this issue**. This optimisation aligns with best practices for Tailwind CSS and can contribute to a smoother user experience.

Thank you for considering this, and I appreciate your efforts in continually improving HyperUI.

**Comment by markmead** [comment]
Hi @techwithshubh, thanks for the issue, do you have any proof of this?

> By making this adjustment, we can significantly improve the efficiency of these components

Not just a StackOverflow post saying it is better, actual benchmarks and evidence that it is **significantly** better.

---

I was using specific transition classes for a while but opted for `transition` it usually has the property I want to transitio, it's also not as lazy as doing `transition-all`.

**Comment by techwithshubh** [comment]
Hi @markmead, Thanks for the reply. I have done the performance analysis for one of the component in [this](https://www.hyperui.dev/components/application-ui/headers) page . Below are the results: 

1. When `transition` class is used

<img width="352" alt="Screenshot 2024-01-07 at 7 20 50 PM" src="https://github.com/markmead/hyperui/assets/153129178/ef556a13-e9ef-41ec-bf95-226b4477009d">

2. When `transition-colors` is used

<img width="376" alt="Screenshot 2024-01-07 at 7 21 52 PM" src="https://github.com/markmead/hyperui/assets/153129178/2238d54e-29ed-4d56-99d4-5c7383968166">

3. When `transition-[color,background-color]` is used

<img width="368" alt="Screenshot 2024-01-07 at 7 22 36 PM" src="https://github.com/markmead/hyperui/assets/153129178/7553d18b-413a-4ee3-bbac-18b96122fc57">

Performance is not **significantly** effected, so instead of Bug, you can change the category to **Nice to have** feature.

**Comment by techwithshubh** [comment]
@markmead , These are the other predefined transition classes provided by tailwind. https://tailwindcss.com/docs/transition-property

**Comment by markmead** [comment]
Yeah I know of their existence. I think based on your tests they should be used, but I'm interested in seeing how they compare with JIT classes.

**Comment by markmead** [comment]
Going to leave this for now. I think it's fine as `transition` and it means users of these components are less likely to run into `hover:` effects not working.
