### ISSUE TITLE
[BUG] Inter font is not applied

### ISSUE THREAD

**Issue by akellbl4** [markmead/hyperui#433]
**Describe the bug**
Font family style in not applied.

**To Reproduce**
1. Go to hyperui.dev
2. See the problem

**Expected behavior**
Text is rendered with Inter font.

**Screenshots**
<img width="1251" alt="image" src="https://github.com/markmead/hyperui/assets/2330682/c9ccd4da-326f-4121-b02a-3852232394c9">.

**Additional context**
I've taken a look and as I can see the class name generated by `Inter` font utility and the class name that is bundled into CSS have different hash. The code for font injections looks correct to me.  Maybe redeploy can help to sync them.

**Comment by akellbl4** [comment]
Deploy should help, confirmed by deploying my fork https://hyperui-git-main-akellbl4.vercel.app/

**Comment by markmead** [comment]
Thanks for investigating! Not sure how that's happened, maybe the previous commit didn't trigger something! 🤷‍♀️ 

Deploying now.
