### ISSUE TITLE
Outside `class` class name declaration

### ISSUE THREAD

**Issue by mahendrameghwal** [markmead/hyperui#434]
**Is your feature request related to a problem? Please describe.**
  <p className="mt-1 text-sm text-gray-700 dark:text-gray-200" dark:hover:bg-gray-800>
        Your product changes have been saved.
      </p> in this dark class is in outside from className

**Comment by markmead** [comment]
What? Do you have an example?

**Comment by mahendrameghwal** [comment]
https://www.hyperui.dev/components/application-ui/alerts  in this second component 
![err](https://github.com/markmead/hyperui/assets/93032228/9b630a56-4fb8-4b1e-a605-84d73bb93581)
