### ISSUE TITLE
Add screen mockups

### ISSUE THREAD

**Issue by tommypurcell** [markmead/hyperui#438]
Hi Mark, 

I was thinking we could add some components for screen type mockups. I've got one now that I could add easily for somewhat of a code editor or browser looking mockup. Don't mind the github api code stuff that was just for my project. People could add any code in there that they would like. It will look like this:
<img width="680" alt="Screenshot 2024-04-08 at 2 45 20 PM" src="https://github.com/markmead/hyperui/assets/120073087/92fa3c9e-bf11-484f-b0b9-c764a578a9d0">

But I'm thinking others could resemble similar to what flowbite has for screen mockups here [https://flowbite.com/docs/components/device-mockups/](https://flowbite.com/docs/components/device-mockups/)

This might require a new collection but I'm interested in your thoughts.

**Comment by markmead** [comment]
Hi @tommypurcell,

Appreciate the interest but I don't think this collection is needed, feels like it would be added for the sake of it. I have been considering a page on the site that just lists examples not tied to a collection. Maybe that could be an option.

**Comment by tommypurcell** [comment]
Sure thing. If you'd like to include the code box or other screen mockups on an example page I'd be happy to share what I have and work on it. 


--
Also, this is probably for a separate issue but I think we could add a "toast" alert. Something similar to this [https://ui.shadcn.com/docs/components/toast](https://ui.shadcn.com/docs/components/toast) from shadcn. I realize that the current alerts can be place anywhere with position but might be cool to have one specifically for like a bottom position. Or have the "toast" functionality — perhaps better fitting for the AlpineJS stuff that you have since it has functionality. Thoughts on this?

**Comment by markmead** [comment]
I did something like that over here - https://js.hyperui.dev/examples/alert-notifications but as for components, that could be an option. I'll take a look at the link you sent.
