### ISSUE TITLE
Add navbar components

### ISSUE THREAD

**Issue by adenlall** [markmead/hyperui#440]
**Is your feature request related to a problem? Please describe.**
I am wondering why there is no ``NavBar`` section while there is ``Footer`` Section, I think this is an important element for an UI library.

**Describe the solution you'd like**
I consider creating a ``NavBar`` section on the ``Application UI`` category and add some components into it 
I would take the initiative and create a pull request regarding this issue.

**I am waiting for your feedback.**

**Comment by markmead** [comment]
https://www.hyperui.dev/components/marketing/headers
