### ISSUE TITLE
Undefined in category URL in show collections list

### ISSUE THREAD

**Issue by DalpatRathore** [markmead/hyperui#449]
**Describe the bug**
There is an `undefined` keyword in the `Show Collections`  navigation URLs for all the component collections.

**To Reproduce**

1. Go to `Show Collections`
2. Click on - any collections component link button, it will navigate to `404 | not found`

**Expected behavior**
 - All the link buttons are navigating to page `404 | not found`, there seem broken URLs, as all the collection components have `undefined` in the URLs, instead should be `marketing` or `application-ui`.
 - E.g. - `footers`  collections right now - `https://www.hyperui.dev/components/undefined/footers`, though manually entering `marketing` in place of undefined works fine `https://www.hyperui.dev/components/marketing/footers`. See the last  screenshot
**Screenshots**
 ## Bug Section - Collections Components
![image](https://github.com/markmead/hyperui/assets/69510006/f9ebab1e-6c58-42a7-8758-ac2fc1dd18af)
## Bug  - 404 | not found
 ![image](https://github.com/markmead/hyperui/assets/69510006/92a54d53-ad1d-4385-a9a1-0d3472531161)

## Before Bug 

![image](https://github.com/markmead/hyperui/assets/69510006/0c4c1fe2-233f-43cd-bdc9-37de296c59a5)

**Desktop (please complete the following information):**

- OS - Windows 11
- Browser - chrome

Thank you

**Comment by markmead** [comment]
Ah, I changed that area with #447, had a feeling I'd miss something! Will get this fixed now, thanks @DalpatRathore!

**Comment by markmead** [comment]
Should be fixed now.

**Comment by DalpatRathore** [comment]
Thanks @markmead,  for the awesome UI/UX components! Your work is truly impressive and makes a big difference.
Keep up the fantastic job!
