### ISSUE TITLE
ReactJs support for components

### ISSUE THREAD

**Issue by USKhokhar** [markmead/hyperui#458]
**Is your feature request related to a problem? Please describe.**

Currently, all the code is written for HTML so when I try to use HyperUI in their React project, I have to manually do the required changes, eg. "class" --> "className", "for" --> "htmlFor", etc.

**Describe the solution you'd like**

What can be done is we start with the basic components where only minor changes are required to make the code react friendly, as mentioned above, many components need changes as minute as changing "class" to "className".

Moreover, we can simply add a button to trigger React code, like it is done in [filters](https://www.hyperui.dev/components/application-ui/filters) for **AlpineJs**:

Ref: 
![image](https://github.com/markmead/hyperui/assets/63156376/dc5a1e38-1a5d-4242-9c77-f96cafd31416)

**Describe alternatives you've considered**

An alternative might be something like HyperUI-React, where we tackle more complex components like Data Tables and Auth forms using some industry-standard libraries.

But that would be an entirely different thing and would distract the user base, I think starting with the current version of HyperUI and gradually updating all components would be a better option.

The initial addition of react support is not much of a work

**Comment by markmead** [comment]
Hi @USKhokhar, this feature already exists. 

If you preview the code by clicking "View" there will be a dropdown where you can select JSX, Vue or HTML. It's not very clear so I'll make improvements to that in the future.
