### ISSUE TITLE
Add navbar component

### ISSUE THREAD

**Issue by R1shabh-Gupta** [markmead/hyperui#462]
I'd like to propose and work on a new component: a **navbar** with integrated search.
Here is the **image preview**: 
<img width="1438" alt="Screenshot 2024-05-17 at 1 45 25 AM" src="https://github.com/markmead/hyperui/assets/109821717/4b4cdcf7-1be5-451b-9c86-f84fe393d82c">

**Comment by markmead** [comment]
Sounds good but don't spend time hooking up the search or anything.
