### ISSUE TITLE
Toggle components not displaying correctly

### ISSUE THREAD

**Issue by heyswayam** [markmead/hyperui#470]
**Describe the bug**
When pasting the code, the toggle components doesn't have a background and looks broken. Also, I have given it a margin-top of 5px, or else the component appears to be clipped.

**To Reproduce**

1- Just copy the code of toggle any component
2- paste it in the tailwind play

**Expected behavior**
The button should load up as shown in the website. 

**Screenshots**
<img width="1145" alt="image" src="https://github.com/markmead/hyperui/assets/96104753/90de2bff-c80a-47b7-9fe7-56f430c05844">
<img width="1345" alt="image" src="https://github.com/markmead/hyperui/assets/96104753/45114b8e-3259-4fd1-87bb-5c10f7783f6b">

<img width="1001" alt="image" src="https://github.com/markmead/hyperui/assets/96104753/d1089410-5743-4039-9436-452183c2ec9d">
<img width="1331" alt="image" src="https://github.com/markmead/hyperui/assets/96104753/4d160812-b79c-4f9a-ab2f-44e8cc2dddc8">

**Additional context**
For the components requiring Alpine js, do I just need to npm install alpinejs and import it at the top of the component?

**Comment by markmead** [comment]
Try adding `flex` to the `<label>` element. You can install Alpine JS or use the CDN - https://alpinejs.dev/start-here

**Comment by markmead** [comment]
Or `inline-block`. Just something to give it a display value.

**Comment by markmead** [comment]
Should be fixed now.

**Comment by heyswayam** [comment]
Yeah that fixes it, should I do a pr adding the class inline-block or you will update it
