### ISSUE TITLE
Suggesting 2 new components

### ISSUE THREAD

**Issue by Aniket1026** [markmead/hyperui#475]
I've been using these 2 types of components in good frequency and i just thought of having them in the library I tend to use usually.

I was not sure so I am discussing both in the same issue.

 ## 1. Table with headings or topics
Tables usually have some heading/topics and some option. So i had this idea of adding it as a component.
The below image is just an example it's not the exact design

<img width="850" alt="hyper-ui-table" src="https://github.com/markmead/hyperui/assets/92184189/61a1e761-e5f6-4c7a-8c73-6c3c5a774a8a">

 <br></br>
## 2. Stats component
Also the current stat components are a bit big and I was thinking of having a bit different and smaller detailed components like this

<img width="273" alt="hyper-ui-stats" src="https://github.com/markmead/hyperui/assets/92184189/007777a3-82f2-4eca-84cb-676deb6919b6">
<br></br>
Well these were the new components i thought of adding I would like to know your view on this. If this aligns with your thoughts and if yes what changes would you suggest. It's also fine if you don't approve these.
<br></br>
Thanks 😄

**Comment by markmead** [comment]
Yeah happy with both of these, might make some small changes but if you wanna get a PR added with these components, that would be great! 🙌

**Comment by Aniket1026** [comment]
Sounds great , I'll start to work for a PR. Would that be fine if I create separate PR for both the components? Because I feel that makes more sense just wanted to make sure from your side too.

**Comment by markmead** [comment]
Yeah, happy with separate PRs.
