### ISSUE TITLE
Adding chart components

### ISSUE THREAD

**Issue by ShahStavan** [markmead/hyperui#480]
Hi @markmead 

I'm planning to add different variants of Charts components such as Line Charts, Bar Charts, and so on. 
Let me know your thoughts on adding these components.

![Example of Line Chart](https://github.com/markmead/hyperui/assets/66560566/7b6e64ad-1d64-42b6-a89f-534f45794ac8)

**Comment by markmead** [comment]
Not interested in this, thanks @ShahStavan!
