### ISSUE TITLE
Components have no styling in preview

### ISSUE THREAD

**Issue by MrFluffycloud** [markmead/hyperui#485]
![image](https://github.com/user-attachments/assets/2c44c78d-6645-43b3-a139-11a56c307d8e)

All the styles are gone

**Comment by markmead** [comment]
Seems to be OK now.

**Comment by MrFluffycloud** [comment]
its still the same, i get this in the console tho
![image](https://github.com/user-attachments/assets/719394dc-93ec-4991-b6ef-c3de613607f5)

**Comment by markmead** [comment]
Huh, that's weird. Are you running it locally? Tailwind CSS styles are coming from their CDN.

**Comment by markmead** [comment]
I assume the CDN isn't loading due to that "ERR_BLOCKED_BY_CLIENT", are you doing something to block CDNs? This is the first I'm hearing of this issue.

**Comment by MrFluffycloud** [comment]
Im using brave..

**Comment by markmead** [comment]
Would take a guess that it's a setting in Brave then as it's fine on Chrome and Brave is based on Chromium.

**Comment by MrFluffycloud** [comment]
Tried it with brave, ms edge, and opera gx.. still the same.
