### ISSUE TITLE
Select component: no border.

### ISSUE THREAD

**Issue by sidouglas** [markmead/hyperui#487]
1. Installed tailwind into create vue app as per https://tailwindcss.com/docs/guides/vite#vue
2. Noted that hyperui uses tailwind v3.4.5 - so downgraded my version.

Diffed my version of v3.4.5 to hyperui.
Where is the select styles coming from:

```
select {
  background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 20 20'%3e%3cpath stroke='%236b7280' stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='M6 8l4 4 4-4'/%3e%3c/svg%3e");
  background-position: right 0.5rem center;
  background-repeat: no-repeat;
  background-size: 1.5em 1.5em;
  padding-right: 2.5rem;
  print-color-adjust: exact;
}
```
That does not exist in tailwind: https://play.tailwindcss.com/6ZjKV5OnC1

https://shottr.cc/s/WUel/SCR-20240805-kptp.png

**Comment by markmead** [comment]
Sorry @sidouglas, there is meant to be a comment at the top of the those components. It's using `@tailwindcss/forms`.
