### ISSUE TITLE
Add visual indicator when component has additional dependency

### ISSUE THREAD

**Issue by hcmlopes** [markmead/hyperui#496]
Would be great to be able to have visual indicator on the component example when that component requires additional dependencies such as the [Testimonials Component 1](https://www.hyperui.dev/components/marketing/testimonials#component-1)

I could put in the work if you let me know how you wish to implement it.

Just a suggestion.

**Comment by markmead** [comment]
Sorry, I don't see the point in that.

**Comment by hcmlopes** [comment]
Just a better user experience in my opinion, no need to click into it. If you don't think it is worth pursuing you can close the issue as it was just a light suggestion.
