### ISSUE TITLE
New product card component

### ISSUE THREAD

**Issue by mohdahsanrazakhan** [markmead/hyperui#499]
## Description:
This product card component contains a product image, price, tile, description, with three buttons Like, Add to Cart, Buy Now.

## Product Card Preview:
![Screenshot 2024-10-02 095227](https://github.com/user-attachments/assets/3e6db185-055c-4f0d-843c-edf80a13c5cb)

## Path for this component:
public/components/marketing-product-cards/

**Comment by Anurag8305** [comment]
@mohdahsanrazakhan Can I work on this issue?

**Comment by mohdahsanrazakhan** [comment]
@Anurag8305 I have PR this issue, you should enhance the feature or add a new component. Follow this [article](https://www.hyperui.dev/blog/how-to-contribute)
