### ISSUE TITLE
MultiLanguage Facility

### ISSUE THREAD

**Issue by Ojas-Arora** [markmead/hyperui#501]
@markmead I want to add Multilanguage Facility to it. Kindly assign me this issue.

**Comment by ShoomanKhatri** [comment]
Can you please , assign this to me?

**Comment by markmead** [comment]
Thanks @ShoomanKhatri but I don't want this added to the site.

**Comment by Ojas-Arora** [comment]
@markmead Any specific issue or work u need in the site?
