### ISSUE TITLE
Bento grid component

### ISSUE THREAD

**Issue by mrpankajpandey** [markmead/hyperui#503]
I would like to add a new Bento Grid layout to the Grid section of HyperUI. This layout will provide a unique way to showcase content using variable-sized grid items, making it visually appealing and flexible for use cases such as portfolios and gallery sections.

**Feature Details:**
- Each grid item will have dynamic sizing and placement, similar to the Bento Box style.
- The grid will support responsive layouts and hover animations.
- I will add a component preview and documentation to explain how to implement and use it.

**Why this feature?**
The Bento Grid layout offers a modern, Pinterest-like grid that could enhance the variety of layouts available in HyperUI.

If this addition is accepted, I will implement it and submit a pull request. Please let me know if there are any specific requirements or suggestions for this component! @markmead 

"Here’s a rough wireframe of the Bento Grid layout I plan to implement. The grid items are of varying sizes, and the layout supports responsive design."
![image](https://github.com/user-attachments/assets/3614b775-beb0-41ad-99f7-4300cb09ccd9)

**Comment by markmead** [comment]
Yeah, I'm intrigued by this @mrpankajpandey! Looking forward to the PR.

**Comment by markmead** [comment]
For requirements, just keep it simple like the components here - https://www.hyperui.dev/components/application-ui/grids

**Comment by mrpankajpandey** [comment]
Hi @markmead 

Thanks for the quick reply! I'm looking forward to working on the PR.
Should I remove images, text like this? 
![image](https://github.com/user-attachments/assets/c38e4cf4-4585-4e2e-8fd8-e47cc673feef)
