### ISSUE TITLE
Breadcrumbs with a menu

### ISSUE THREAD

**Issue by mohit2404** [markmead/hyperui#505]
we have 2 breadcrumbs component
- dropdown option lets it easier to navigate to a specific page without going back
- all option will be visible for possible pages that exists at that level

**Comment by SaurabhKumar171** [comment]
Hi, can i work on this issue , can you assign this to me ?

**Comment by markmead** [comment]
Hi @mohit2404, do you have an example?

**Comment by mohit2404** [comment]
> Hi @mohit2404, do you have an example?

I was thinking to add a component like this, 
https://dribbble.com/shots/22473574-Daily-UI-056-Breadcrumbs

**Comment by nVedaVarshit** [comment]
Hi @mohit2404 
I can do it.

**Comment by markmead** [comment]
Any real world examples? @mohit2404

**Comment by mohit2404** [comment]
@markmead  as of now I personally have not seen any but it is good to have for peoples who might want to use it in their projects

**Comment by markmead** [comment]
I'm gonna pass on this component then @mohit2404. I don't see why anyone would use this as a breadcrumb, or a menu. I typically don't get inspiration from Dribbble for this reason.
