### ISSUE TITLE
GitHub templates

### ISSUE THREAD

**Issue by mrpankajpandey** [markmead/hyperui#506]
# Feature Request
We need to add both an Issue Template and a Pull Request Template to the repository. This will standardize the way contributors create issues and submit pull requests, making it easier for maintainers to review and manage contributions.

## Feature Details
1. Issue Template:
        Create Create Create a ISSUE_TEMPLATE directory inside .github.
        Add a default issue template file for bug reports, feature requests, and general queries.

2.  Pull Request Template:
      Create a PULL_REQUEST_TEMPLATE.md file inside the .github directory.
      Include sections for a brief summary, changes made, testing steps, and a checklist to ensure contributions meet the project 
      guidelines.

## Directory Structure
 📁 .github
 ┣ 📂 ISSUE_TEMPLATE
 ┃ ┣ 📜 feature_request.md
 ┃ ┣ 📜 bug_report.md
 ┗ 📜 PULL_REQUEST_TEMPLATE.md

Like this it's amazing features
![image](https://github.com/user-attachments/assets/f627e728-91fe-4f97-b5f6-6f4e702d2242)

**Comment by markmead** [comment]
Thanks @mrpankajpandey I had these before but people didn't use them.

**Comment by mrpankajpandey** [comment]
Ok sir thanks for feedback, please look at my PR #504  @markmead
