### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by nidhi752** [markmead/hyperui#510]
Hi, I observed that the website currently does not have a dark mode, which can be a valuable feature for enhancing user experience. Dark mode helps in reducing eye strain, especially in low-light environments or during nighttime browsing. It also contributes to better visibility and overall comfort for users who prefer a darker interface. I would like to implement this feature to ensure that the website is more accessible and user-friendly, catering to different preferences and improving the overall usability.
Please assign this to me under Hackoctoberfest'24

**Comment by markmead** [comment]
Hi @nidhi752, thanks for the suggestion. I've added and then removed dark mode a few times, therefore I'm going to pass on adding it again.
