### ISSUE TITLE
Feature - Add new testimonial component

### ISSUE THREAD

**Issue by HarshArora-1205** [markmead/hyperui#511]
Hi, I recently worked with embla carousel and its plugins to create a similar testimonials component in React.js. When I saw testimonials components I thought we can add another carousel testimonial section, with fading effect. So, the active slide has full opacity, while other slides have 15% opacity. Also since the component is in center layout, for rtl, I coded it to just reverse text directions of reviews, instead of div layouts. 

Here is the component:

https://github.com/user-attachments/assets/fb6d23f7-cd09-4ef7-a8d4-4e2f9516d0ad

Also this component is based on embla carousel instead of keen slider, which doesn't impact much on the project and is actively maintained and completely open source.

Though, if needed, keen slider can also be used for the same.
Hope this component adds some value to HyperUI. And all constructive feedbacks and thoughts are welcomed.

**Comment by HarshArora-1205** [comment]
@markmead Could you review this?

**Comment by markmead** [comment]
Looks good. I'd prefer it to use `keen-slider` and I feel the 15% opacity is way too low. It would also be good to keep the navigation buttons from hitting the left/right side.

**Comment by HarshArora-1205** [comment]
Alright, I will change it to keen slider. Only ease in using embla is that, they provide plug-ins directly. Thus, it don't require much of effort in javascript.

Will do the required changes by today.

**Comment by HarshArora-1205** [comment]
#513 
Hi, updated code accordingly and raised a PR.
