### ISSUE TITLE
Add scroll back to top button 

### ISSUE THREAD

**Issue by Sneha123-zudo** [markmead/hyperui#512]
I want to add scroll back to top button the website it will enhance the UI of the website and the website will look good. 
Please assign me this issue under Hacktoberfest'24 , i am intrested in contribuiting to this issue.

**Comment by markmead** [comment]
Not a huge fan of those but I'd be interested in seeing what you come up with @Sneha123-zudo

**Comment by Atharva-developer** [comment]
@markmead I can add the button scroll back to the top, by giving it a good transition. Kindly assign me this issue as it'll be the first in hacktoberfest.
looking forward to contribute!

**Comment by the-sukhsingh** [comment]
Hi! I noticed this issue and believed I can help. I’ve implemented a similar feature on my [portfolio website](https://the-sukhsingh.github.io/portfolio/). On my site, the element appears when scrolling down and hides when scrolling back up or clicking it. I’m confident I can apply this functionality here as well. I’d love the opportunity to contribute and help solve this issue. Looking forward to your response!
