### ISSUE TITLE
Cart component with plus and minus icons

### ISSUE THREAD

**Issue by mohdahsanrazakhan** [markmead/hyperui#530]
# Description:
I see majority of the cart which contain product increment and decrement icons with input field. That's why I'll add new cart component which contain plus and minus icons.

# Issue Preview:
![image](https://github.com/user-attachments/assets/0e35ce31-6f10-4adb-a398-dfcd7d8332ca)

# Expected Preview:
![image](https://github.com/user-attachments/assets/d5848458-a298-4bee-b6a4-eec11aeac5ed)

**Comment by markmead** [comment]
> I see majority of the cart which contain product increment and decrement icons

I don't, not for a popup cart. Hence why I didn't go with it for this component. If people want to add it, then there are https://www.hyperui.dev/components/application-ui/quantity-inputs they could use.
