### ISSUE TITLE
Add Footer Component with Multiple Layout Variants

### ISSUE THREAD

**Issue by ADITYA-KHADE** [markmead/hyperui#535]
I’d like to contribute a footer component to HyperUI. Footers are essential for website navigation and branding, typically containing links, contact information, social media icons, and copyright notices. This component would provide a flexible, configurable footer configuration that can easily be adapted for different applications.

The footer component will include:

1] Basic Footer Layout: A modest footer with links and copyright information.
2] Multi-Column Layout: Sections for rapid connections, contact information, and social network indicators.
3] Responsive Design: A layout that arranges columns into rows on mobile for optimal viewing on all screen resolutions.
4] Dark Mode Support: Styles compatible with Tailwind's dark mode tool, allowing the footer to integrate smoothly into dark-themed projects.
5] Social networking integration: placeholder emblems for prominent social networking services, customized to complement the footer theme.

Technical Details:
1] Built using Tailwind CSS for quick modification.
2] Responsive: Designed to perform well across multiple screen sizes.
3] Dark Mode: Uses Tailwind's dark mode features for a smooth light/dark transition.

Please let me know if there are any more features or variants you would want to see in this component. I am open to recommendations to ensure it brings together well inside HyperUI’s component library.

**Comment by markmead** [comment]
Hi @ADITYA-KHADE this doesn't sound like it adds anything new to the existing footer collection. Do you have an example of how it would look?
