### ISSUE TITLE
Mechanism to track changes to components

### ISSUE THREAD

**Issue by jvantuyl** [markmead/hyperui#546]
As a developer, I can read a changelog with the best of them.  However, it's a bit tedious to wade through the changes to keep components up-to-date.

I think this is even worse for non-developers & very junior folks.  If you take the website at face value and just copy-and-paste, there's not really much to go on to know if something has changed.

## Potential Goals
- Automation of generating and consuming the change data.
- Human-understandable information to give a full picture of changes over time (i.e. How old is the current version?  What version did this change have?  Which version is newer?)
- Versioning follows copy-pasta.
- Easily generate a URL for the code in question from the versioning information.

## Ideas
Here are some ideas that might achieve those goals.

### Version or Date + Commit in UI
This would at least give something someone could check.  I don't think there are currently releases (at least, I couldn't find any tags), so a datestamp could be used in the absence of that.  The inclusion of the commit is there so the person can track down where it changed.  Presumably the datestamp would be the datestamp of said commit.

#### Pros
- At least something is available to work with, so you don't have to manually diff the two components to see if there are changes.
- Could automate adding that metadata.
- Version and/or Date give some way to compare "newness" (where just the commit would give equality comparison but not really allow fully ordering various copy-pasta components over time).
- Could be automated in a pre-commit hook and/or a CI pipeline.

#### Cons
- Lack of version could potentially make it hard for humans to get a picture of changes over time.
- Not easily automated from the user side.

### Comment with Version Code
For the HTML of every component, add some kind of release tag.  These could probably be managed automatically via scripts if formatted cleverly enough.

For example, let's say that each component file has an HTML comment like this:
```html
<!-- hyper_ui_component application_ui/toggles/1 0.0.11-bd3a674  -->
```

Basically, the first element of the comment is just text to make these easy to find with automated tools.

The second is the path to the HTML in `public`.

The third is a semver version number synthesized by the major and minor releases with the patch release calculated by counting the GIT commits that touch that path.  (I don't think you currently have release numbers, so I just put 0.0 in there).  We could use a datestamp instead if any manual versioning is strongly undesired.

#### Pros
- Can be fully automated for generation.
- Can automate a process to detect "old" components.
- Information to track down commit and file is there.
- Synthesized patch revision reduces adminstrative load.
- Follows copypasta

#### Cons
- Maybe these would confuse people?
- Version tracking / running the script during release needs to be done.
- Person still has to be smart enough to use the URL

### Full Github URL
That's mostly the same information that's available in the URL, so maybe it would be better to do something like this:
```html
<!-- Component sourced from https://github.com/markmead/hyperui/blob/bd3a674/public/components/application-ui-toggles/1.html#v0.0.11 -->
```

The fragment is just there for automated tools to avoid accidentally messing with similar links that aren't autogenerated and to capture the version ordering that is lost with just the URL.

I don't know the URL syntax, but we might even be able to hit a page that showed a diff against the current release.

#### Pros
- All the benefits of "Comment with Version Code" above.
- URL leaves no doubt where to find updated component HTML.
- Github doesn't seem to dislike unrecognized fragments (most sites don't).
- Throwaway text at the beginning makes meaning of tag clearer.

#### Cons
- If we used the diff link, that might be likely to change in the future.

### Hash Tagging
An alternative way to do this would be to use a truncated (SHA3?) hash of the actual text.  If we wanted to be clever, we could start out with a placeholder for the hash (say `XXXXXXXX`).  Hash the file and drop that in and now you've got a pretty solid way to track down changes.

This might be compact enough that you could avoid the comment altogether and just put an innocuous attribute in the HTML or even a dummy class value.

Consider...
```html
<div x-hyperui-component="XXXXXXXX" class="...">...</div>
```
...or...
```html
<div class="... hyperui_XXXXXXXX">...</div>
```

#### Pros
- More compact.
- Attribute / Class tagging is less likely to get dropped when copying the pasta.

#### Cons
- Not so easy to turn into a useful URL.
- Not easy to tell which of two versions is newer.

### Automated Detection

Could write a tool that scanned a file hierarchy (i.e. user's app source), finds these tags, and summarizes how out-of-date these components are.  Maybe even put an extension into Buildbot?  Probably wouldn't be too bad if written in a language that delivers binaries, cross-platform with a stable API.  (Go comes to mind.)

#### Pros
- Easy to tell what's changed and how much work I have to do.
- Great for CI pipelines.
- Could make the "Hash Tagging" option more usable

#### Cons
- Devs must maintain tools.
- Users must install tool, keep up-to-date, and actually use it.

## Closing Thoughts
I love these components.  But the thought of a codebase with hundreds of diverged copies of them that are snapshots taken over years... well... I shudder.  I feel like a small bit of work here could go a long way—especially considering how automated the site generation already is.

**Comment by jvantuyl** [comment]
As an aside, the "count of git commits" thing for patch versioning can be done on a file with the command:
```bash
git rev-list HEAD -- public/components/application-ui-toggles/1.html
```

That gives the list of commits (with the top one being the commit you'd want to use the hash for).  You can count them trivially in most languages (or `| wc -l` if you're sticking to shell).

**Comment by markmead** [comment]
I'll close it as I have absolutely no interest in this. Even if 100 people made issues for it (Which no one has ever made an issue for it), I still wouldn't do it. 

It's a small, uncomplicated project providing uncomplicated components. That's it.

**Comment by jvantuyl** [comment]
@markmead Just for the record, the whole "ongoing maintenance" thing came up in the context of evaluating component libraries.  Reading between the lines, I think somebody on my team has PTSD from some other prior experience (involving React, I suspect... for reasons).

Just the statement that these shouldn't require any special maintenance is enough for me.  Though maybe put something in the FAQ for anyone who else who assumes a component libraries implies a heavy maintenance load.
