### ISSUE TITLE
New Component Request: Badge

### ISSUE THREAD

**Issue by Amishakumari544** [markmead/hyperui#68]
**Badge**

show the count of a given data using badge
**Examples of Component**

https://tailwindui.com/components/application-ui/elements/badges
https://tailwind-elements.com/docs/standard/components/badges/
https://getbootstrap.com/docs/5.1/components/badge/

**Comment by Amishakumari544** [comment]
Can I work on this issue @markmead ?

**Comment by markmead** [comment]
Hey @Amishakumari544 they do already exist, but I've labelled them as "Tags" which is incorrect. Welcome to make a PR to change them to "Badges" and add a few more to the collection 🙌

https://www.hyperui.dev/components/tags

**Comment by markmead** [comment]
I've updated the component name in #69 to "Badges", just need some new components now 😉

**Comment by Amishakumari544** [comment]
Hey, @markmead i will create pr soon! 😄
