### ISSUE TITLE
Application UI Components

### ISSUE THREAD

**Issue by markmead** [markmead/hyperui#73]
I'll be creating a range of application UI components for HyperUI.

**Collection Ideas**
- [x] Side Menus
- [ ] Nav Menus
- [ ] Tab Menus
- [ ] Cards
- [ ] Tables
- [x] Headers

Have a request? Let me know in the comments 👇

**Comment by markmead** [comment]
Thanks @vhscom I will take a look! 🙌

**Comment by markmead** [comment]
First release has been deployed! 🥳 #75

**Comment by markmead** [comment]
Going to be working on the second release:

- [ ] Stat Cards
- [ ] Headers

Looking to get some of these live by the end of the day.

**Comment by nquandt** [comment]
@markmead I noticed on the application UI pages, form submissions actually cause an action inside of the iframes, not sure if this is intended usage or a vulnerability.

Repro: Go to the second application UI example, click the logout button inside the iframe

**Comment by markmead** [comment]
Thanks @nquandt I didn't spot that! Shouldn't be an issue but I'll get a fix deployed.
