### ISSUE TITLE
Forms should explicitly require @tailwindcss/forms plugin

### ISSUE THREAD

**Issue by albertbronsky** [markmead/hyperui#8]
It should be noted somewhere on this page (https://hyperui.dev/components/forms) that it requires installing `@tailwindcss/forms` plugin to properly reset selects and inputs to make them look like shown in the demo.

Other than that, HyperUI is an awesome project - keep up the good work! :)

**Comment by markmead** [comment]
Nice idea, thanks for sharing! 

I'll get this added.

**Comment by markmead** [comment]
Updated with #9
